[flake8]
max-line-length = 120
exclude = .git,__pycache__,build,dist

[isort]
profile = black
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool:black]
line-length = 120
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
    \..*
  | build
  | dist
  | __pycache__
  | .venv
  | .git
  | .mypy_cache
  | .pytest_cache
  | .tox
  | .eggs
  | .idea
  | .vscode
)/
'''
