SELECT
    R.ID,
    'HACUE_AMED',
    r.PACIENTE_ID,
    r.FECHAVACUNACION,
    PE.ID,
    PE.NUMEROIDENTIFICACION,
    pe.FECHANACIMIENTO,
    pe.ESTADO,
    pe.CTSEXO_ID,
    d.DESCRIPCION AS SEXO,
    pe.FECHACREACION,
    pe.FECHAMODIFICACION,
    R.ENTIDAD_ID,
    R.ESQUEMAVACUNACION_ID,
    P.ID,
    P.ACTIVO,
    P.ESTADO,
    P.FECHACREACION,
    P.FECHAMODIFICACION,
    R.PUNTOVACUNACION_ID,
    R.LOTE,
    R.FASEVACUNACION,
    r.REFUERZO
FROM HCUE_AMED.REGISTROVACUNACION R
    INNER JOIN HCUE_AMED.PACIENTE P ON R.PACIENTE_ID = P.ID
    INNER JOIN HCUE_SISTEMA.PERSONA PE ON PE.ID = p.PERSONA_ID
    LEFT JOIN HCUE_CATALOGOS.DETALLECATALOGO d ON d.ID = pe.CTSEXO_ID
WHERE
    R.FECHAVACUNACION > TO_DATE ('2021-01-01', 'yyyy-mm-dd')
    AND R.FECHAVACUNACION < TO_DATE ('2025-01-01', 'yyyy-mm-dd')
    AND rownum < 10